export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA = "FETCH_DATA";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
export const FILTER_CATEGORY = "FILTER_CATEGORY";
export const SET_CURRENT_QUIZ_ID = "SET_CURRENT_QUIZ_ID";
